ci: remove sccache rustc-wrapper from committed config
CI Ubuntu runners do not have sccache installed by default. Hardcoding
[build] rustc-wrapper = "sccache" in committed .cargo/config.toml caused
all cargo invocations on CI to fail with:

    error: could not execute process `sccache .../clippy-driver ... rustc -vV` (never executed)
    Caused by: No such file or directory (os error 2)

Move sccache opt-in to developer-local shell env (RUSTC_WRAPPER=sccache)
or user-level ~/.cargo/config.toml. CI now uses plain rustc.

Refs: PR #1 Clippy/Build CI failure root cause.